# -*- coding: utf-8 -*-
"""PROJECT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17P_KsZi9HzoV5ZYD2hE8GyfzjbZyn1Oe
"""

import pandas as pd

import numpy as np

from statsmodels.tsa.arima.model import ARIMA

from statsmodels.tsa.statespace.sarimax import SARIMAX

from xgboost import XGBRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error

from sklearn.preprocessing import StandardScaler



df = pd.read_csv("PJM_Load_hourly.csv")

df['Datetime'] = pd.to_datetime(df['Datetime'])

df = df.set_index("Datetime")



col = df.select_dtypes(include=['float64', 'int64']).columns[0]

df = df[[col]].rename(columns={col: "load"})



df = df.resample("H").mean().interpolate()

df["theta_1"] = df["load"].shift(1)

df["theta_2"] = df["load"].shift(24)

df["theta_3"] = df["load"].shift(168)



df = df.dropna()



train_size = int(len(df)*0.8)

train = df.iloc[:train_size]

test  = df.iloc[train_size:]



y_train, y_test = train["load"], test["load"]

X_train = train[["theta_1","theta_2","theta_3"]]

X_test  = test[["theta_1","theta_2","theta_3"]]



def metrics(y_true, y_pred):

    MAE  = mean_absolute_error(y_true, y_pred)

    RMSE = np.sqrt(mean_squared_error(y_true, y_pred))

    MAPE = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

    return MAE, RMSE, MAPE



har_model = ARIMA(y_train, exog=X_train, order=(1,0,1))

har_res = har_model.fit()



har_pred = har_res.predict(start=y_test.index[0], end=y_test.index[-1], exog=X_test)



har_mae, har_rmse, har_mape = metrics(y_test, har_pred)



print("\n HAR-ARIMA PERFORMANCE ")

print(f"MAE  : {har_mae:.3f}")

print(f"RMSE : {har_rmse:.3f}")

print(f"MAPE : {har_mape:.2f}%")



import matplotlib.pyplot as plt

import seaborn as sns



sns.set(style="whitegrid", context="talk")



plt.figure(figsize=(18, 6))

sns.lineplot(x=y_test.index, y=y_test, label="Actual", color="blue", linewidth=2)

sns.lineplot(x=y_test.index, y=har_pred, label="HAR-ARIMA Prediction", color="red", linewidth=2)



plt.title("Actual vs HAR-ARIMA Predictions", fontsize=20)

plt.xlabel("Time", fontsize=16)

plt.ylabel("Value", fontsize=16)

plt.legend(fontsize=14)

plt.tight_layout()

plt.show()



har_residuals = y_test - har_pred



plt.figure(figsize=(18, 5))

sns.lineplot(x=y_test.index, y=har_residuals, color="purple", linewidth=2)

plt.axhline(0, linestyle="--", color="black")



plt.title("HAR-ARIMA Residuals Over Time", fontsize=20)

plt.xlabel("Time", fontsize=16)

plt.ylabel("Residual", fontsize=16)

plt.tight_layout()

plt.show()



plt.figure(figsize=(10, 5))

sns.histplot(har_residuals, bins=30, kde=True, color="green")



plt.title("HAR-ARIMA Residual Distribution", fontsize=20)

plt.xlabel("Residual", fontsize=16)

plt.ylabel("Frequency", fontsize=16)

plt.tight_layout()

plt.show()



sarima_model = SARIMAX(y_train, order=(1,0,1), seasonal_order=(1,0,1,24))

sarima_res = sarima_model.fit()



sarima_pred = sarima_res.predict(start=y_test.index[0], end=y_test.index[-1])



sarima_mae, sarima_rmse, sarima_mape = metrics(y_test, sarima_pred)



print("\n BASELINE SARIMA PERFORMANCE ")

print(f"MAE  : {sarima_mae:.3f}")

print(f"RMSE : {sarima_rmse:.3f}")

print(f"MAPE : {sarima_mape:.2f}%")



import matplotlib.pyplot as plt

import seaborn as sns





sns.set(style="whitegrid", context="talk")



plt.figure(figsize=(18, 6))



sns.lineplot(x=y_test.index, y=y_test, label="Actual", linewidth=2, color="blue")

sns.lineplot(x=y_test.index, y=sarima_pred, label="SARIMA Prediction", linewidth=2, color="red")



plt.title("Actual vs SARIMA Predicted Values", fontsize=20)

plt.xlabel("Time", fontsize=16)

plt.ylabel("Value", fontsize=16)

plt.legend(fontsize=14)

plt.tight_layout()

plt.show()



residuals = y_test - sarima_pred



plt.figure(figsize=(18, 5))

sns.lineplot(x=residuals.index, y=residuals, color="purple", linewidth=2)

plt.axhline(0, linestyle="--", color="black", linewidth=1)



plt.title("SARIMA Residuals Over Time", fontsize=20)

plt.xlabel("Time", fontsize=16)

plt.ylabel("Residual", fontsize=16)

plt.tight_layout()

plt.show()



plt.figure(figsize=(10, 5))

sns.histplot(residuals, kde=True, color="green", bins=30)



plt.title("Residual Distribution", fontsize=20)

plt.xlabel("Residual", fontsize=16)

plt.ylabel("Frequency", fontsize=16)

plt.tight_layout()

plt.show()



scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled  = scaler.transform(X_test)



xgb_model = XGBRegressor(

    n_estimators=400,

    learning_rate=0.05,

    max_depth=6,

    subsample=0.8,

    colsample_bytree=0.8,

    objective="reg:squarederror"

)



xgb_model.fit(X_train_scaled, y_train)

xgb_pred = xgb_model.predict(X_test_scaled)



xgb_mae, xgb_rmse, xgb_mape = metrics(y_test, xgb_pred)



print("\n XGBOOST BASELINE PERFORMANCE")

print(f"MAE  : {xgb_mae:.3f}")

print(f"RMSE : {xgb_rmse:.3f}")

print(f"MAPE : {xgb_mape:.2f}%")



import matplotlib.pyplot as plt

import seaborn as sns

import numpy as np



sns.set(style="whitegrid", context="talk")



plt.figure(figsize=(18, 6))



sns.lineplot(x=y_test.index, y=y_test, label="Actual", color="blue", linewidth=2)

sns.lineplot(x=y_test.index, y=xgb_pred, label="XGBoost Prediction", color="red", linewidth=2)



plt.title("Actual vs XGBoost Predicted Values", fontsize=20)

plt.xlabel("Time", fontsize=16)

plt.ylabel("Value", fontsize=16)

plt.legend(fontsize=14)

plt.tight_layout()

plt.show()



plt.figure(figsize=(10, 7))



sns.scatterplot(x=y_test, y=xgb_pred, color="purple", s=60, alpha=0.7)

plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], "k--", linewidth=2)



plt.title("Actual vs Predicted (XGBoost)", fontsize=20)

plt.xlabel("Actual", fontsize=16)

plt.ylabel("Predicted", fontsize=16)

plt.tight_layout()

plt.show()



xgb_residuals = y_test - xgb_pred



plt.figure(figsize=(18, 5))

sns.lineplot(x=y_test.index, y=xgb_residuals, color="green", linewidth=2)

plt.axhline(0, linestyle="--", color="black")



plt.title("XGBoost Residuals Over Time", fontsize=20)

plt.xlabel("Time", fontsize=16)

plt.ylabel("Residual", fontsize=16)

plt.tight_layout()

plt.show()



plt.figure(figsize=(10, 5))

sns.histplot(xgb_residuals, bins=30, kde=True, color="orange")



plt.title("Residual Distribution (XGBoost)", fontsize=20)

plt.xlabel("Residual", fontsize=16)

plt.ylabel("Frequency", fontsize=16)

plt.tight_layout()

plt.show()



summary = pd.DataFrame({

    "Model": ["SARIMA", "HAR-ARIMA", "XGBoost"],

    "MAE": [sarima_mae, har_mae, xgb_mae],

    "RMSE": [sarima_rmse, har_rmse, xgb_rmse],

    "MAPE%": [sarima_mape, har_mape, xgb_mape]

})



print("\n\n FINAL MODEL COMPARISON TABLE n")

print(summary.to_string(index=False))